### PR TITLE
implement Base.seekstart and Base.seekend

### PR DESCRIPTION
**Pull request by bicycle1885**

### CODE REVIEW

**Comment by alyst** [comment]
Thanks for the PR!

I'm checking this branch with `RData`. The stream is opened this way:
```julia
function load(f::File{format"RData"}; kwoptions...)
    open(GzipDecompressionStream, filename(f), "r") do gzio
        load(Stream(f, gzio), kwoptions)
    end
end
```

But then I'm having:
```
Reading minimal RData: Error During Test
  Test threw an exception of type ErrorException
  Expression: (load("$(testdir)/data/minimal_ascii.rda"))["df"] == df
  zlib error: incorrect header check (code: -3)
  Stacktrace:
   [1] changemode!(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}, ::Symbol) at /fs/home/<>/.julia/v0.6/TranscodingStreams/src/stream.jl:612
   [2] callprocess(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}, ::TranscodingStreams.Buffer, ::TranscodingStreams.Buffer) at /fs/home/<>/.julia/v0.6/TranscodingStreams/src/stream.jl:543
   [3] fillbuffer(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}) at /fs/home/<>/.julia/v0.6/TranscodingStreams/src/stream.jl:479
   [4] eof(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}) at /fs/home/<>/.julia/v0.6/TranscodingStreams/src/stream.jl:165
   [5] read(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}, ::Type{UInt8}) at /fs/home/<>/.julia/v0.6/TranscodingStreams/src/stream.jl:259
   [6] detect_rdata(::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}) at /fs/home/<>/.julia/v0.6/FileIO/src/registry.jl:12
   [7] load(::FileIO.Stream{FileIO.DataFormat{:RData},TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,IOStream}}, ::Array{Any,1}) at /fs/home/<>/.julia/v0.6/RData/src/RData.jl:51
   [8] open(::RData.##10#11{Array{Any,1},FileIO.File{FileIO.DataFormat{:RData}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompression,S} where S<:IO}, ::String, ::String) at /fs/home/<>/.julia/v0.6/TranscodingStreams/src/stream.jl:139
   [9] load(::FileIO.File{FileIO.DataFormat{:RData}}) at /fs/home/<>/.julia/v0.6/RData/src/RData.jl:44
   [10] #load#13(::Array{Any,1}, ::Function, ::String) at /fs/home/<>/.julia/v0.6/FileIO/src/loadsave.jl:52
   [11] macro expansion at /fs/gpfs03/lv06/pool/pool-innate-bioinfo2/<>/.julia/v0.6/RData/test/RDA.jl:23 [inlined]
   [12] macro expansion at ./test.jl:860 [inlined]
   [13] anonymous at ./<missing>:?
```

**Comment by bicycle1885** [comment]
Hmm, I'm not sure why this happens. Can you create a small reproducible code to debug it?

**Comment by alyst** [comment]
I've found the reason: some RData files were uncompressed. Somehow `gzopen()` was tolerant to this and just switched off decompression. Now I'm checking the magic GZip number:
```julia
function load(f::File{format"RData"}; kwoptions...)
    open(filename(f), "r") do io
        gzipped = read(io, UInt16) == 0x8B1F # check GZip magic number FIXME endianness?
        seekstart(io)
        fs = Stream(f, gzipped ? GzipDecompressionStream(io) : io)
        load(fs, kwoptions)
    end
end
```

Is it the correct way? I'm worried that I'm not closing `GzipDecompressionStream(io)`, though `io` itself is closed.

**Comment by bicycle1885** [comment]
That will not release resources allocated in zlib, and so you'll need to release it somehow. A simple solution would be:
```julia
function isgzip(io)
    mark(io)
    x = read(io, UInt8)
    y = read(io, UInt8)
    gzipped = (x, y) == (0x1f, 0x8b)
    reset(io)
    return gzipped
end

function load(f::File{format"RData"}; kwoptions...)
    file = open(filename(f))
    try
        if isgzip(file)
            file = GzipDecompressionStream(file)
        end
        return load(Stream(f, file), kwoptions)
    catch
        rethrow()
    finally
        close(stream)
    end
end
```

**Comment by alyst** [comment]
Thanks!
Actually, I like `open() do io ... end` pattern since it helps avoiding explicit exception handling.
I wonder if it's possible to have `transcode(f, T, io) where {T<:IO}`, so that one could write:
```julia
function load(f::File{format"RData"}; kwoptions...)
    open(filename(f), "r") do io
        if isgzip(io)
            return transcode(GzipDecompressionStream, io) do gzio
                load(Stream(f, gzio), kwoptions)
            end
        else
            return load(Stream(f, io), kwoptions)
        end
    end
end
```

**Comment by bicycle1885** [comment]
No, it doesn't work. open-do and try-catch-finally are equivalent in this case.

**Pull request merged**
